### ISSUE TITLE
Remove the icons apart from "Google Developer Student Clubs Techno NJR"

### ISSUE THREAD

**Issue by subinsk** [matrixiocommunity/matrixio#1]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76201673/198366983-f4ab0ee2-20df-4e31-9c22-b294e1580370.png">

**Comment by Sujal-Sahu** [comment]
Hii @subinsk  please close this issue as you merged my branch with main branch.

**Comment by subinsk** [comment]
Okay sure @Sujal-Sahu. Great Work!
